---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ca-org2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger
      role: ca
      org: org2
      name: ca
  template:
    metadata:
      labels:
        app: hyperledger
        role: ca
        org: org2
        name: ca
    spec:
      containers:
        - name: ca
          image: hyperledger/fabric-ca:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GODEBUG
              value: netdns=go
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca.org2.example.com
            - name: FABRIC_CA_SERVER_PORT
              value: "7054"
            # - name: FABRIC_CA_SERVER_CA_CERTFILE
            #   value: /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            # - name: FABRIC_CA_SERVER_CA_KEYFILE
            #   value: ${ORG1TLSCA_FABRIC_CA_SERVER_CA_KEYFILE}
            - name:  FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            # - name:  FABRIC_CA_SERVER_TLS_CERTFILE
            #   value: /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            # - name:  FABRIC_CA_SERVER_TLS_KEYFILE
            #   value: /etc/hyperledger/fabric-ca-server-config/1ed5c86791dab80b530421f1231b0ef252913a61c5ed810bacc2be1b1b0f1603_sk
          ports:
            - containerPort: 7054
          command: ["sh", "-c"]
          args:
            - "fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/*cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/*_sk"
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: certificate
              subPath: crypto-config/peerOrganizations/org2.example.com/ca/
            #- mountPath: /etc/hyperledger/fabric-ca-server
            #  name: certificate
            #  subPath: fabric-ca-server/
      volumes:
        - name: certificate
          persistentVolumeClaim:
            claimName: default-resources-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ca-org2
spec:
  selector:
    app: hyperledger
    role: ca
    org: org2
    name: ca
  type: NodePort
  ports:
    - name: endpoint
      protocol: TCP
      port: 7054
      targetPort: 7054
      nodePort: 30200
