# ------------------------------------------- orderer ledgers -------------------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-orderer0-ledgers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-orderer1-ledgers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-orderer2-ledgers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

