# ------------------------------------------- org2 dind -------------------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-peer0-org2-dind-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-peer1-org2-dind-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

# ------------------------------------------- org2 couchdb -------------------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-peer0-org2-couchdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-peer1-org2-couchdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

# ------------------------------------------- org2 ledgers -------------------------------------------
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-peer0-org2-ledgers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: default-peer1-org2-ledgers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
  volumeMode: Filesystem

