---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-resources-pv
  namespace: default
spec:
  nfs:
    path: /default/resources
    server: 172.16.100.11
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: default-resources-pvc
    namespace: default
  storageClassName: nfs
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-resources-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

