---
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: composer-rest-server
type: Opaque
data:
  COMPOSER_APIKEY: "RHNmNmFxblVuMkNGNTJ0eG1aNm5UaldV"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: composer-rest-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composer-rest-server
  template:
    metadata:
      labels:
        app: composer-rest-server
    spec:
      containers:
        - name: server
          image: hyperledger/composer-rest-server:0.20.8
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
          env:
            - name: COMPOSER_CARD
              value: bob@transfer-example
            - name: COMPOSER_NAMESPACES
              value: never
          envFrom:
            - secretRef:
                name: composer-rest-server
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: resources
              subPath: .composer
              mountPath: /home/composer/.composer
            - name: resources
              mountPath: /data
      volumes:
        - name: resources
          persistentVolumeClaim:
            claimName: default-composer-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: composer-rest-server
spec:
  selector:
    app: composer-rest-server
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: bob-composer-rest-server
spec:
  rules:
    - host: bob-composer-rest-server.example.com
      http:
        paths:
          - path:
            backend:
              serviceName: composer-rest-server
              servicePort: http
