---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composer-cli
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composer-cli
  template:
    metadata:
      labels:
        app: composer-cli
    spec:
      containers:
        - name: cli
          image: hyperledger/composer-cli:0.20.8
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
            - name: resources
              subPath: composer/data
              mountPath: /home/composer/.composer
            - name: resources
              mountPath: /data
      volumes:
        - name: resources
          persistentVolumeClaim:
            claimName: default-composer-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composer-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composer-playground
  template:
    metadata:
      labels:
        app: composer-playground
    spec:
      containers:
        - name: composer-playground
          image: hyperledger/composer-playground:0.20.8
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: resources
              subPath: composer/data
              mountPath: /home/composer/.composer
            - name: resources
              mountPath: /data
      volumes:
        - name: resources
          persistentVolumeClaim:
            claimName: default-composer-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: composer-playground
spec:
  selector:
    app: composer-playground
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: composer-playground
spec:
  rules:
    - host: composer-playground.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: composer-playground
              servicePort: http
